// Mocks generated by Mockito 5.4.4 from annotations
// in youtube_music_downloader/test/features/downloader_engine/presentation/providers/download_queue_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:extractor/src/generated/youtube_dl_api.g.dart' as _i2;
import 'package:extractor/src/models/download_progress.dart' as _i7;
import 'package:extractor/src/models/download_state.dart' as _i8;
import 'package:extractor/src/youtube_dl_flutter.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:youtube_music_downloader/features/downloads_history/data/models/download_task.dart'
    as _i5;
import 'package:youtube_music_downloader/features/downloads_history/domain/repositories/downloads_history_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInitResult_0 extends _i1.SmartFake implements _i2.InitResult {
  _FakeInitResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVersionInfo_1 extends _i1.SmartFake implements _i2.VersionInfo {
  _FakeVersionInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateResult_2 extends _i1.SmartFake implements _i2.UpdateResult {
  _FakeUpdateResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoInfo_3 extends _i1.SmartFake implements _i2.VideoInfo {
  _FakeVideoInfo_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDownloadResult_4 extends _i1.SmartFake
    implements _i2.DownloadResult {
  _FakeDownloadResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_5 extends _i1.SmartFake implements Duration {
  _FakeDuration_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObject_6 extends _i1.SmartFake implements Object {
  _FakeObject_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DownloadsHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadsHistoryRepository extends _i1.Mock
    implements _i3.DownloadsHistoryRepository {
  @override
  _i4.Future<_i5.DownloadTask?> getTaskById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [id],
        ),
        returnValue: _i4.Future<_i5.DownloadTask?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.DownloadTask?>.value(),
      ) as _i4.Future<_i5.DownloadTask?>);

  @override
  _i4.Future<_i5.DownloadTask?> getNextPendingTask() => (super.noSuchMethod(
        Invocation.method(
          #getNextPendingTask,
          [],
        ),
        returnValue: _i4.Future<_i5.DownloadTask?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.DownloadTask?>.value(),
      ) as _i4.Future<_i5.DownloadTask?>);

  @override
  _i4.Future<void> saveTask(_i5.DownloadTask? task) => (super.noSuchMethod(
        Invocation.method(
          #saveTask,
          [task],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTaskProgress(
    int? id, {
    required double? progress,
    required String? speed,
    required String? eta,
    required _i5.DownloadStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTaskProgress,
          [id],
          {
            #progress: progress,
            #speed: speed,
            #eta: eta,
            #status: status,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateTaskStatus(
    int? id,
    _i5.DownloadStatus? status, {
    String? errorMessage,
    String? actualQuality,
    String? targetPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTaskStatus,
          [
            id,
            status,
          ],
          {
            #errorMessage: errorMessage,
            #actualQuality: actualQuality,
            #targetPath: targetPath,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.DownloadTask>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.DownloadTask>>.value(<_i5.DownloadTask>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i5.DownloadTask>>.value(<_i5.DownloadTask>[]),
      ) as _i4.Future<List<_i5.DownloadTask>>);

  @override
  _i4.Stream<List<_i5.DownloadTask>> watchAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #watchAllTasks,
          [],
        ),
        returnValue: _i4.Stream<List<_i5.DownloadTask>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.DownloadTask>>.empty(),
      ) as _i4.Stream<List<_i5.DownloadTask>>);

  @override
  _i4.Future<void> deleteTask(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [YoutubeDLFlutter].
///
/// See the documentation for Mockito's code generation for more information.
class MockYoutubeDLFlutter extends _i1.Mock implements _i6.YoutubeDLFlutter {
  @override
  _i4.Stream<_i7.DownloadProgress> get onProgress => (super.noSuchMethod(
        Invocation.getter(#onProgress),
        returnValue: _i4.Stream<_i7.DownloadProgress>.empty(),
        returnValueForMissingStub: _i4.Stream<_i7.DownloadProgress>.empty(),
      ) as _i4.Stream<_i7.DownloadProgress>);

  @override
  _i4.Stream<_i8.DownloadState> get onStateChanged => (super.noSuchMethod(
        Invocation.getter(#onStateChanged),
        returnValue: _i4.Stream<_i8.DownloadState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i8.DownloadState>.empty(),
      ) as _i4.Stream<_i8.DownloadState>);

  @override
  _i4.Stream<_i6.DownloadError> get onError => (super.noSuchMethod(
        Invocation.getter(#onError),
        returnValue: _i4.Stream<_i6.DownloadError>.empty(),
        returnValueForMissingStub: _i4.Stream<_i6.DownloadError>.empty(),
      ) as _i4.Stream<_i6.DownloadError>);

  @override
  _i4.Stream<_i6.LogMessage> get onLog => (super.noSuchMethod(
        Invocation.getter(#onLog),
        returnValue: _i4.Stream<_i6.LogMessage>.empty(),
        returnValueForMissingStub: _i4.Stream<_i6.LogMessage>.empty(),
      ) as _i4.Stream<_i6.LogMessage>);

  @override
  _i4.Future<_i2.InitResult> initialize({
    bool? enableFFmpeg = true,
    bool? enableAria2c = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #enableFFmpeg: enableFFmpeg,
            #enableAria2c: enableAria2c,
          },
        ),
        returnValue: _i4.Future<_i2.InitResult>.value(_FakeInitResult_0(
          this,
          Invocation.method(
            #initialize,
            [],
            {
              #enableFFmpeg: enableFFmpeg,
              #enableAria2c: enableAria2c,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.InitResult>.value(_FakeInitResult_0(
          this,
          Invocation.method(
            #initialize,
            [],
            {
              #enableFFmpeg: enableFFmpeg,
              #enableAria2c: enableAria2c,
            },
          ),
        )),
      ) as _i4.Future<_i2.InitResult>);

  @override
  _i4.Future<_i2.VersionInfo> getVersion() => (super.noSuchMethod(
        Invocation.method(
          #getVersion,
          [],
        ),
        returnValue: _i4.Future<_i2.VersionInfo>.value(_FakeVersionInfo_1(
          this,
          Invocation.method(
            #getVersion,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.VersionInfo>.value(_FakeVersionInfo_1(
          this,
          Invocation.method(
            #getVersion,
            [],
          ),
        )),
      ) as _i4.Future<_i2.VersionInfo>);

  @override
  _i4.Future<_i2.UpdateResult> updateYoutubeDL(
          {_i2.UpdateChannel? channel = _i2.UpdateChannel.stable}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateYoutubeDL,
          [],
          {#channel: channel},
        ),
        returnValue: _i4.Future<_i2.UpdateResult>.value(_FakeUpdateResult_2(
          this,
          Invocation.method(
            #updateYoutubeDL,
            [],
            {#channel: channel},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.UpdateResult>.value(_FakeUpdateResult_2(
          this,
          Invocation.method(
            #updateYoutubeDL,
            [],
            {#channel: channel},
          ),
        )),
      ) as _i4.Future<_i2.UpdateResult>);

  @override
  _i4.Future<_i2.VideoInfo> getVideoInfo(String? url) => (super.noSuchMethod(
        Invocation.method(
          #getVideoInfo,
          [url],
        ),
        returnValue: _i4.Future<_i2.VideoInfo>.value(_FakeVideoInfo_3(
          this,
          Invocation.method(
            #getVideoInfo,
            [url],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.VideoInfo>.value(_FakeVideoInfo_3(
          this,
          Invocation.method(
            #getVideoInfo,
            [url],
          ),
        )),
      ) as _i4.Future<_i2.VideoInfo>);

  @override
  _i4.Future<_i2.VideoInfo> getVideoInfoWithOptions(
    String? url,
    Map<String, String>? options,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoInfoWithOptions,
          [
            url,
            options,
          ],
        ),
        returnValue: _i4.Future<_i2.VideoInfo>.value(_FakeVideoInfo_3(
          this,
          Invocation.method(
            #getVideoInfoWithOptions,
            [
              url,
              options,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.VideoInfo>.value(_FakeVideoInfo_3(
          this,
          Invocation.method(
            #getVideoInfoWithOptions,
            [
              url,
              options,
            ],
          ),
        )),
      ) as _i4.Future<_i2.VideoInfo>);

  @override
  _i4.Future<_i2.DownloadResult> download(_i2.DownloadRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [request],
        ),
        returnValue: _i4.Future<_i2.DownloadResult>.value(_FakeDownloadResult_4(
          this,
          Invocation.method(
            #download,
            [request],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DownloadResult>.value(_FakeDownloadResult_4(
          this,
          Invocation.method(
            #download,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.DownloadResult>);

  @override
  _i4.Future<bool> cancelDownload(String? processId) => (super.noSuchMethod(
        Invocation.method(
          #cancelDownload,
          [processId],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isInitialized() => (super.noSuchMethod(
        Invocation.method(
          #isInitialized,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DownloadProgress].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadProgress extends _i1.Mock implements _i7.DownloadProgress {
  @override
  String get processId => (super.noSuchMethod(
        Invocation.getter(#processId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#processId),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#processId),
        ),
      ) as String);

  @override
  double get progress => (super.noSuchMethod(
        Invocation.getter(#progress),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  int get etaInSeconds => (super.noSuchMethod(
        Invocation.getter(#etaInSeconds),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  double get progressFraction => (super.noSuchMethod(
        Invocation.getter(#progressFraction),
        returnValue: 0.0,
        returnValueForMissingStub: 0.0,
      ) as double);

  @override
  Duration get eta => (super.noSuchMethod(
        Invocation.getter(#eta),
        returnValue: _FakeDuration_5(
          this,
          Invocation.getter(#eta),
        ),
        returnValueForMissingStub: _FakeDuration_5(
          this,
          Invocation.getter(#eta),
        ),
      ) as Duration);
}

/// A class which mocks [DownloadState].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadState extends _i1.Mock implements _i8.DownloadState {
  @override
  String get processId => (super.noSuchMethod(
        Invocation.getter(#processId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#processId),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#processId),
        ),
      ) as String);

  @override
  _i8.DownloadStateType get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i8.DownloadStateType.started,
        returnValueForMissingStub: _i8.DownloadStateType.started,
      ) as _i8.DownloadStateType);
}

/// A class which mocks [DownloadError].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadError extends _i1.Mock implements _i6.DownloadError {
  @override
  String get processId => (super.noSuchMethod(
        Invocation.getter(#processId),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#processId),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#processId),
        ),
      ) as String);

  @override
  String get error => (super.noSuchMethod(
        Invocation.getter(#error),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#error),
        ),
        returnValueForMissingStub: _i9.dummyValue<String>(
          this,
          Invocation.getter(#error),
        ),
      ) as String);
}

/// A class which mocks [DownloadResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadResult extends _i1.Mock implements _i2.DownloadResult {
  @override
  _i2.OperationStatus get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i2.OperationStatus.success,
        returnValueForMissingStub: _i2.OperationStatus.success,
      ) as _i2.OperationStatus);

  @override
  set status(_i2.OperationStatus? _status) => super.noSuchMethod(
        Invocation.setter(
          #status,
          _status,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set outputPath(String? _outputPath) => super.noSuchMethod(
        Invocation.setter(
          #outputPath,
          _outputPath,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set errorMessage(String? _errorMessage) => super.noSuchMethod(
        Invocation.setter(
          #errorMessage,
          _errorMessage,
        ),
        returnValueForMissingStub: null,
      );

  @override
  Object encode() => (super.noSuchMethod(
        Invocation.method(
          #encode,
          [],
        ),
        returnValue: _FakeObject_6(
          this,
          Invocation.method(
            #encode,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeObject_6(
          this,
          Invocation.method(
            #encode,
            [],
          ),
        ),
      ) as Object);
}
