// Mocks generated by Mockito 5.4.4 from annotations
// in youtube_music_downloader/test/features/download_setup/data/repositories/download_setup_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:collection' as _i9;

import 'package:http_parser/http_parser.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:youtube_explode_dart/src/channels/channels.dart' as _i4;
import 'package:youtube_explode_dart/src/common/common.dart' as _i8;
import 'package:youtube_explode_dart/src/playlists/playlist.dart' as _i7;
import 'package:youtube_explode_dart/src/playlists/playlist_client.dart' as _i3;
import 'package:youtube_explode_dart/src/playlists/playlist_id.dart' as _i10;
import 'package:youtube_explode_dart/src/reverse_engineering/models/fragment.dart'
    as _i16;
import 'package:youtube_explode_dart/src/search/search_client.dart' as _i5;
import 'package:youtube_explode_dart/src/videos/streams/mixins/hls_stream_info.dart'
    as _i15;
import 'package:youtube_explode_dart/src/videos/video_client.dart' as _i2;
import 'package:youtube_explode_dart/src/videos/videos.dart' as _i6;
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVideoClient_0 extends _i1.SmartFake implements _i2.VideoClient {
  _FakeVideoClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaylistClient_1 extends _i1.SmartFake
    implements _i3.PlaylistClient {
  _FakePlaylistClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelClient_2 extends _i1.SmartFake implements _i4.ChannelClient {
  _FakeChannelClient_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSearchClient_3 extends _i1.SmartFake implements _i5.SearchClient {
  _FakeSearchClient_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamClient_4 extends _i1.SmartFake implements _i6.StreamClient {
  _FakeStreamClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClosedCaptionClient_5 extends _i1.SmartFake
    implements _i6.ClosedCaptionClient {
  _FakeClosedCaptionClient_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCommentsClient_6 extends _i1.SmartFake
    implements _i6.CommentsClient {
  _FakeCommentsClient_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideo_7 extends _i1.SmartFake implements _i6.Video {
  _FakeVideo_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamManifest_8 extends _i1.SmartFake
    implements _i6.StreamManifest {
  _FakeStreamManifest_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaylist_9 extends _i1.SmartFake implements _i7.Playlist {
  _FakePlaylist_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoId_10 extends _i1.SmartFake implements _i6.VideoId {
  _FakeVideoId_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChannelId_11 extends _i1.SmartFake implements _i4.ChannelId {
  _FakeChannelId_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThumbnailSet_12 extends _i1.SmartFake implements _i8.ThumbnailSet {
  _FakeThumbnailSet_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnmodifiableListView_13<E> extends _i1.SmartFake
    implements _i9.UnmodifiableListView<E> {
  _FakeUnmodifiableListView_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEngagement_14 extends _i1.SmartFake implements _i8.Engagement {
  _FakeEngagement_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$VideoCopyWith_15<$Res> extends _i1.SmartFake
    implements _i6.$VideoCopyWith<$Res> {
  _Fake$VideoCopyWith_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlaylistId_16 extends _i1.SmartFake implements _i10.PlaylistId {
  _FakePlaylistId_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$PlaylistCopyWith_17<$Res> extends _i1.SmartFake
    implements _i7.$PlaylistCopyWith<$Res> {
  _Fake$PlaylistCopyWith_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ThumbnailSetCopyWith_18<$Res> extends _i1.SmartFake
    implements _i8.$ThumbnailSetCopyWith<$Res> {
  _Fake$ThumbnailSetCopyWith_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_19 extends _i1.SmartFake implements Uri {
  _FakeUri_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamContainer_20 extends _i1.SmartFake
    implements _i6.StreamContainer {
  _FakeStreamContainer_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFileSize_21 extends _i1.SmartFake implements _i6.FileSize {
  _FakeFileSize_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBitrate_22 extends _i1.SmartFake implements _i6.Bitrate {
  _FakeBitrate_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoResolution_23 extends _i1.SmartFake
    implements _i6.VideoResolution {
  _FakeVideoResolution_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFramerate_24 extends _i1.SmartFake implements _i6.Framerate {
  _FakeFramerate_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMediaType_25 extends _i1.SmartFake implements _i11.MediaType {
  _FakeMediaType_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [YoutubeExplode].
///
/// See the documentation for Mockito's code generation for more information.
class MockYoutubeExplode extends _i1.Mock implements _i12.YoutubeExplode {
  @override
  _i2.VideoClient get videos => (super.noSuchMethod(
        Invocation.getter(#videos),
        returnValue: _FakeVideoClient_0(
          this,
          Invocation.getter(#videos),
        ),
        returnValueForMissingStub: _FakeVideoClient_0(
          this,
          Invocation.getter(#videos),
        ),
      ) as _i2.VideoClient);

  @override
  set videos(_i2.VideoClient? _videos) => super.noSuchMethod(
        Invocation.setter(
          #videos,
          _videos,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.PlaylistClient get playlists => (super.noSuchMethod(
        Invocation.getter(#playlists),
        returnValue: _FakePlaylistClient_1(
          this,
          Invocation.getter(#playlists),
        ),
        returnValueForMissingStub: _FakePlaylistClient_1(
          this,
          Invocation.getter(#playlists),
        ),
      ) as _i3.PlaylistClient);

  @override
  set playlists(_i3.PlaylistClient? _playlists) => super.noSuchMethod(
        Invocation.setter(
          #playlists,
          _playlists,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.ChannelClient get channels => (super.noSuchMethod(
        Invocation.getter(#channels),
        returnValue: _FakeChannelClient_2(
          this,
          Invocation.getter(#channels),
        ),
        returnValueForMissingStub: _FakeChannelClient_2(
          this,
          Invocation.getter(#channels),
        ),
      ) as _i4.ChannelClient);

  @override
  set channels(_i4.ChannelClient? _channels) => super.noSuchMethod(
        Invocation.setter(
          #channels,
          _channels,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.SearchClient get search => (super.noSuchMethod(
        Invocation.getter(#search),
        returnValue: _FakeSearchClient_3(
          this,
          Invocation.getter(#search),
        ),
        returnValueForMissingStub: _FakeSearchClient_3(
          this,
          Invocation.getter(#search),
        ),
      ) as _i5.SearchClient);

  @override
  set search(_i5.SearchClient? _search) => super.noSuchMethod(
        Invocation.setter(
          #search,
          _search,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [VideoClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoClient extends _i1.Mock implements _i2.VideoClient {
  @override
  _i6.StreamClient get streamsClient => (super.noSuchMethod(
        Invocation.getter(#streamsClient),
        returnValue: _FakeStreamClient_4(
          this,
          Invocation.getter(#streamsClient),
        ),
        returnValueForMissingStub: _FakeStreamClient_4(
          this,
          Invocation.getter(#streamsClient),
        ),
      ) as _i6.StreamClient);

  @override
  _i6.ClosedCaptionClient get closedCaptions => (super.noSuchMethod(
        Invocation.getter(#closedCaptions),
        returnValue: _FakeClosedCaptionClient_5(
          this,
          Invocation.getter(#closedCaptions),
        ),
        returnValueForMissingStub: _FakeClosedCaptionClient_5(
          this,
          Invocation.getter(#closedCaptions),
        ),
      ) as _i6.ClosedCaptionClient);

  @override
  _i6.CommentsClient get commentsClient => (super.noSuchMethod(
        Invocation.getter(#commentsClient),
        returnValue: _FakeCommentsClient_6(
          this,
          Invocation.getter(#commentsClient),
        ),
        returnValueForMissingStub: _FakeCommentsClient_6(
          this,
          Invocation.getter(#commentsClient),
        ),
      ) as _i6.CommentsClient);

  @override
  _i6.StreamClient get streams => (super.noSuchMethod(
        Invocation.getter(#streams),
        returnValue: _FakeStreamClient_4(
          this,
          Invocation.getter(#streams),
        ),
        returnValueForMissingStub: _FakeStreamClient_4(
          this,
          Invocation.getter(#streams),
        ),
      ) as _i6.StreamClient);

  @override
  _i6.CommentsClient get comments => (super.noSuchMethod(
        Invocation.getter(#comments),
        returnValue: _FakeCommentsClient_6(
          this,
          Invocation.getter(#comments),
        ),
        returnValueForMissingStub: _FakeCommentsClient_6(
          this,
          Invocation.getter(#comments),
        ),
      ) as _i6.CommentsClient);

  @override
  _i13.Future<_i6.Video> get(dynamic videoId) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [videoId],
        ),
        returnValue: _i13.Future<_i6.Video>.value(_FakeVideo_7(
          this,
          Invocation.method(
            #get,
            [videoId],
          ),
        )),
        returnValueForMissingStub: _i13.Future<_i6.Video>.value(_FakeVideo_7(
          this,
          Invocation.method(
            #get,
            [videoId],
          ),
        )),
      ) as _i13.Future<_i6.Video>);

  @override
  _i13.Future<_i6.RelatedVideosList?> getRelatedVideos(_i6.Video? video) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelatedVideos,
          [video],
        ),
        returnValue: _i13.Future<_i6.RelatedVideosList?>.value(),
        returnValueForMissingStub: _i13.Future<_i6.RelatedVideosList?>.value(),
      ) as _i13.Future<_i6.RelatedVideosList?>);
}

/// A class which mocks [StreamClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamClient extends _i1.Mock implements _i6.StreamClient {
  @override
  _i13.Future<_i6.StreamManifest> getManifest(
    dynamic videoId, {
    bool? fullManifest = false,
    List<_i6.YoutubeApiClient>? ytClients,
    bool? requireWatchPage = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManifest,
          [videoId],
          {
            #fullManifest: fullManifest,
            #ytClients: ytClients,
            #requireWatchPage: requireWatchPage,
          },
        ),
        returnValue:
            _i13.Future<_i6.StreamManifest>.value(_FakeStreamManifest_8(
          this,
          Invocation.method(
            #getManifest,
            [videoId],
            {
              #fullManifest: fullManifest,
              #ytClients: ytClients,
              #requireWatchPage: requireWatchPage,
            },
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i6.StreamManifest>.value(_FakeStreamManifest_8(
          this,
          Invocation.method(
            #getManifest,
            [videoId],
            {
              #fullManifest: fullManifest,
              #ytClients: ytClients,
              #requireWatchPage: requireWatchPage,
            },
          ),
        )),
      ) as _i13.Future<_i6.StreamManifest>);

  @override
  _i13.Future<String> getHttpLiveStreamUrl(_i6.VideoId? videoId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHttpLiveStreamUrl,
          [videoId],
        ),
        returnValue: _i13.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #getHttpLiveStreamUrl,
            [videoId],
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<String>.value(_i14.dummyValue<String>(
          this,
          Invocation.method(
            #getHttpLiveStreamUrl,
            [videoId],
          ),
        )),
      ) as _i13.Future<String>);

  @override
  _i13.Stream<List<int>> get(_i6.StreamInfo? streamInfo) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [streamInfo],
        ),
        returnValue: _i13.Stream<List<int>>.empty(),
        returnValueForMissingStub: _i13.Stream<List<int>>.empty(),
      ) as _i13.Stream<List<int>>);
}

/// A class which mocks [PlaylistClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylistClient extends _i1.Mock implements _i3.PlaylistClient {
  @override
  _i13.Future<_i7.Playlist> get(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i13.Future<_i7.Playlist>.value(_FakePlaylist_9(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i13.Future<_i7.Playlist>.value(_FakePlaylist_9(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
      ) as _i13.Future<_i7.Playlist>);

  @override
  _i13.Stream<_i6.Video> getVideos(dynamic id) => (super.noSuchMethod(
        Invocation.method(
          #getVideos,
          [id],
        ),
        returnValue: _i13.Stream<_i6.Video>.empty(),
        returnValueForMissingStub: _i13.Stream<_i6.Video>.empty(),
      ) as _i13.Stream<_i6.Video>);
}

/// A class which mocks [Video].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideo extends _i1.Mock implements _i6.Video {
  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  bool get hasWatchPage => (super.noSuchMethod(
        Invocation.getter(#hasWatchPage),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.VideoId get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakeVideoId_10(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _FakeVideoId_10(
          this,
          Invocation.getter(#id),
        ),
      ) as _i6.VideoId);

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  String get author => (super.noSuchMethod(
        Invocation.getter(#author),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#author),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#author),
        ),
      ) as String);

  @override
  _i4.ChannelId get channelId => (super.noSuchMethod(
        Invocation.getter(#channelId),
        returnValue: _FakeChannelId_11(
          this,
          Invocation.getter(#channelId),
        ),
        returnValueForMissingStub: _FakeChannelId_11(
          this,
          Invocation.getter(#channelId),
        ),
      ) as _i4.ChannelId);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  _i8.ThumbnailSet get thumbnails => (super.noSuchMethod(
        Invocation.getter(#thumbnails),
        returnValue: _FakeThumbnailSet_12(
          this,
          Invocation.getter(#thumbnails),
        ),
        returnValueForMissingStub: _FakeThumbnailSet_12(
          this,
          Invocation.getter(#thumbnails),
        ),
      ) as _i8.ThumbnailSet);

  @override
  _i9.UnmodifiableListView<String> get keywords => (super.noSuchMethod(
        Invocation.getter(#keywords),
        returnValue: _FakeUnmodifiableListView_13<String>(
          this,
          Invocation.getter(#keywords),
        ),
        returnValueForMissingStub: _FakeUnmodifiableListView_13<String>(
          this,
          Invocation.getter(#keywords),
        ),
      ) as _i9.UnmodifiableListView<String>);

  @override
  _i8.Engagement get engagement => (super.noSuchMethod(
        Invocation.getter(#engagement),
        returnValue: _FakeEngagement_14(
          this,
          Invocation.getter(#engagement),
        ),
        returnValueForMissingStub: _FakeEngagement_14(
          this,
          Invocation.getter(#engagement),
        ),
      ) as _i8.Engagement);

  @override
  bool get isLive => (super.noSuchMethod(
        Invocation.getter(#isLive),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<({String? album, String? artist, Uri? image, String? song})>
      get musicData => (super.noSuchMethod(
            Invocation.getter(#musicData),
            returnValue: <({
              String? album,
              String? artist,
              Uri? image,
              String? song
            })>[],
            returnValueForMissingStub: <({
              String? album,
              String? artist,
              Uri? image,
              String? song
            })>[],
          ) as List<
              ({String? album, String? artist, Uri? image, String? song})>);

  @override
  _i6.$VideoCopyWith<_i6.Video> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$VideoCopyWith_15<_i6.Video>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$VideoCopyWith_15<_i6.Video>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i6.$VideoCopyWith<_i6.Video>);
}

/// A class which mocks [Playlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlaylist extends _i1.Mock implements _i7.Playlist {
  @override
  String get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#url),
        ),
      ) as String);

  @override
  _i10.PlaylistId get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakePlaylistId_16(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _FakePlaylistId_16(
          this,
          Invocation.getter(#id),
        ),
      ) as _i10.PlaylistId);

  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#title),
        ),
      ) as String);

  @override
  String get author => (super.noSuchMethod(
        Invocation.getter(#author),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#author),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#author),
        ),
      ) as String);

  @override
  String get description => (super.noSuchMethod(
        Invocation.getter(#description),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#description),
        ),
      ) as String);

  @override
  _i8.ThumbnailSet get thumbnails => (super.noSuchMethod(
        Invocation.getter(#thumbnails),
        returnValue: _FakeThumbnailSet_12(
          this,
          Invocation.getter(#thumbnails),
        ),
        returnValueForMissingStub: _FakeThumbnailSet_12(
          this,
          Invocation.getter(#thumbnails),
        ),
      ) as _i8.ThumbnailSet);

  @override
  _i8.Engagement get engagement => (super.noSuchMethod(
        Invocation.getter(#engagement),
        returnValue: _FakeEngagement_14(
          this,
          Invocation.getter(#engagement),
        ),
        returnValueForMissingStub: _FakeEngagement_14(
          this,
          Invocation.getter(#engagement),
        ),
      ) as _i8.Engagement);

  @override
  _i7.$PlaylistCopyWith<_i7.Playlist> get copyWith => (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$PlaylistCopyWith_17<_i7.Playlist>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub: _Fake$PlaylistCopyWith_17<_i7.Playlist>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i7.$PlaylistCopyWith<_i7.Playlist>);
}

/// A class which mocks [StreamManifest].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamManifest extends _i1.Mock implements _i6.StreamManifest {
  @override
  _i9.UnmodifiableListView<_i6.StreamInfo> get streams => (super.noSuchMethod(
        Invocation.getter(#streams),
        returnValue: _FakeUnmodifiableListView_13<_i6.StreamInfo>(
          this,
          Invocation.getter(#streams),
        ),
        returnValueForMissingStub: _FakeUnmodifiableListView_13<_i6.StreamInfo>(
          this,
          Invocation.getter(#streams),
        ),
      ) as _i9.UnmodifiableListView<_i6.StreamInfo>);

  @override
  _i9.UnmodifiableListView<_i6.AudioStreamInfo> get audio =>
      (super.noSuchMethod(
        Invocation.getter(#audio),
        returnValue: _FakeUnmodifiableListView_13<_i6.AudioStreamInfo>(
          this,
          Invocation.getter(#audio),
        ),
        returnValueForMissingStub:
            _FakeUnmodifiableListView_13<_i6.AudioStreamInfo>(
          this,
          Invocation.getter(#audio),
        ),
      ) as _i9.UnmodifiableListView<_i6.AudioStreamInfo>);

  @override
  _i9.UnmodifiableListView<_i6.VideoStreamInfo> get video =>
      (super.noSuchMethod(
        Invocation.getter(#video),
        returnValue: _FakeUnmodifiableListView_13<_i6.VideoStreamInfo>(
          this,
          Invocation.getter(#video),
        ),
        returnValueForMissingStub:
            _FakeUnmodifiableListView_13<_i6.VideoStreamInfo>(
          this,
          Invocation.getter(#video),
        ),
      ) as _i9.UnmodifiableListView<_i6.VideoStreamInfo>);

  @override
  _i9.UnmodifiableListView<_i6.MuxedStreamInfo> get muxed =>
      (super.noSuchMethod(
        Invocation.getter(#muxed),
        returnValue: _FakeUnmodifiableListView_13<_i6.MuxedStreamInfo>(
          this,
          Invocation.getter(#muxed),
        ),
        returnValueForMissingStub:
            _FakeUnmodifiableListView_13<_i6.MuxedStreamInfo>(
          this,
          Invocation.getter(#muxed),
        ),
      ) as _i9.UnmodifiableListView<_i6.MuxedStreamInfo>);

  @override
  _i9.UnmodifiableListView<_i6.AudioOnlyStreamInfo> get audioOnly =>
      (super.noSuchMethod(
        Invocation.getter(#audioOnly),
        returnValue: _FakeUnmodifiableListView_13<_i6.AudioOnlyStreamInfo>(
          this,
          Invocation.getter(#audioOnly),
        ),
        returnValueForMissingStub:
            _FakeUnmodifiableListView_13<_i6.AudioOnlyStreamInfo>(
          this,
          Invocation.getter(#audioOnly),
        ),
      ) as _i9.UnmodifiableListView<_i6.AudioOnlyStreamInfo>);

  @override
  _i9.UnmodifiableListView<_i6.VideoOnlyStreamInfo> get videoOnly =>
      (super.noSuchMethod(
        Invocation.getter(#videoOnly),
        returnValue: _FakeUnmodifiableListView_13<_i6.VideoOnlyStreamInfo>(
          this,
          Invocation.getter(#videoOnly),
        ),
        returnValueForMissingStub:
            _FakeUnmodifiableListView_13<_i6.VideoOnlyStreamInfo>(
          this,
          Invocation.getter(#videoOnly),
        ),
      ) as _i9.UnmodifiableListView<_i6.VideoOnlyStreamInfo>);

  @override
  _i9.UnmodifiableListView<_i15.HlsStreamInfo> get hls => (super.noSuchMethod(
        Invocation.getter(#hls),
        returnValue: _FakeUnmodifiableListView_13<_i15.HlsStreamInfo>(
          this,
          Invocation.getter(#hls),
        ),
        returnValueForMissingStub:
            _FakeUnmodifiableListView_13<_i15.HlsStreamInfo>(
          this,
          Invocation.getter(#hls),
        ),
      ) as _i9.UnmodifiableListView<_i15.HlsStreamInfo>);
}

/// A class which mocks [ThumbnailSet].
///
/// See the documentation for Mockito's code generation for more information.
class MockThumbnailSet extends _i1.Mock implements _i8.ThumbnailSet {
  @override
  String get lowResUrl => (super.noSuchMethod(
        Invocation.getter(#lowResUrl),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#lowResUrl),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#lowResUrl),
        ),
      ) as String);

  @override
  String get mediumResUrl => (super.noSuchMethod(
        Invocation.getter(#mediumResUrl),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#mediumResUrl),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#mediumResUrl),
        ),
      ) as String);

  @override
  String get highResUrl => (super.noSuchMethod(
        Invocation.getter(#highResUrl),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#highResUrl),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#highResUrl),
        ),
      ) as String);

  @override
  String get standardResUrl => (super.noSuchMethod(
        Invocation.getter(#standardResUrl),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#standardResUrl),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#standardResUrl),
        ),
      ) as String);

  @override
  String get maxResUrl => (super.noSuchMethod(
        Invocation.getter(#maxResUrl),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#maxResUrl),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#maxResUrl),
        ),
      ) as String);

  @override
  String get videoId => (super.noSuchMethod(
        Invocation.getter(#videoId),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#videoId),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#videoId),
        ),
      ) as String);

  @override
  _i8.$ThumbnailSetCopyWith<_i8.ThumbnailSet> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$ThumbnailSetCopyWith_18<_i8.ThumbnailSet>(
          this,
          Invocation.getter(#copyWith),
        ),
        returnValueForMissingStub:
            _Fake$ThumbnailSetCopyWith_18<_i8.ThumbnailSet>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i8.$ThumbnailSetCopyWith<_i8.ThumbnailSet>);
}

/// A class which mocks [VideoOnlyStreamInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoOnlyStreamInfo extends _i1.Mock
    implements _i6.VideoOnlyStreamInfo {
  @override
  _i6.VideoId get videoId => (super.noSuchMethod(
        Invocation.getter(#videoId),
        returnValue: _FakeVideoId_10(
          this,
          Invocation.getter(#videoId),
        ),
        returnValueForMissingStub: _FakeVideoId_10(
          this,
          Invocation.getter(#videoId),
        ),
      ) as _i6.VideoId);

  @override
  int get tag => (super.noSuchMethod(
        Invocation.getter(#tag),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  Uri get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _FakeUri_19(
          this,
          Invocation.getter(#url),
        ),
        returnValueForMissingStub: _FakeUri_19(
          this,
          Invocation.getter(#url),
        ),
      ) as Uri);

  @override
  _i6.StreamContainer get container => (super.noSuchMethod(
        Invocation.getter(#container),
        returnValue: _FakeStreamContainer_20(
          this,
          Invocation.getter(#container),
        ),
        returnValueForMissingStub: _FakeStreamContainer_20(
          this,
          Invocation.getter(#container),
        ),
      ) as _i6.StreamContainer);

  @override
  _i6.FileSize get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: _FakeFileSize_21(
          this,
          Invocation.getter(#size),
        ),
        returnValueForMissingStub: _FakeFileSize_21(
          this,
          Invocation.getter(#size),
        ),
      ) as _i6.FileSize);

  @override
  _i6.Bitrate get bitrate => (super.noSuchMethod(
        Invocation.getter(#bitrate),
        returnValue: _FakeBitrate_22(
          this,
          Invocation.getter(#bitrate),
        ),
        returnValueForMissingStub: _FakeBitrate_22(
          this,
          Invocation.getter(#bitrate),
        ),
      ) as _i6.Bitrate);

  @override
  String get videoCodec => (super.noSuchMethod(
        Invocation.getter(#videoCodec),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#videoCodec),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#videoCodec),
        ),
      ) as String);

  @override
  String get qualityLabel => (super.noSuchMethod(
        Invocation.getter(#qualityLabel),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#qualityLabel),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#qualityLabel),
        ),
      ) as String);

  @override
  _i6.VideoQuality get videoQuality => (super.noSuchMethod(
        Invocation.getter(#videoQuality),
        returnValue: _i6.VideoQuality.unknown,
        returnValueForMissingStub: _i6.VideoQuality.unknown,
      ) as _i6.VideoQuality);

  @override
  _i6.VideoResolution get videoResolution => (super.noSuchMethod(
        Invocation.getter(#videoResolution),
        returnValue: _FakeVideoResolution_23(
          this,
          Invocation.getter(#videoResolution),
        ),
        returnValueForMissingStub: _FakeVideoResolution_23(
          this,
          Invocation.getter(#videoResolution),
        ),
      ) as _i6.VideoResolution);

  @override
  _i6.Framerate get framerate => (super.noSuchMethod(
        Invocation.getter(#framerate),
        returnValue: _FakeFramerate_24(
          this,
          Invocation.getter(#framerate),
        ),
        returnValueForMissingStub: _FakeFramerate_24(
          this,
          Invocation.getter(#framerate),
        ),
      ) as _i6.Framerate);

  @override
  List<_i16.Fragment> get fragments => (super.noSuchMethod(
        Invocation.getter(#fragments),
        returnValue: <_i16.Fragment>[],
        returnValueForMissingStub: <_i16.Fragment>[],
      ) as List<_i16.Fragment>);

  @override
  _i11.MediaType get codec => (super.noSuchMethod(
        Invocation.getter(#codec),
        returnValue: _FakeMediaType_25(
          this,
          Invocation.getter(#codec),
        ),
        returnValueForMissingStub: _FakeMediaType_25(
          this,
          Invocation.getter(#codec),
        ),
      ) as _i11.MediaType);

  @override
  String get videoQualityLabel => (super.noSuchMethod(
        Invocation.getter(#videoQualityLabel),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#videoQualityLabel),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#videoQualityLabel),
        ),
      ) as String);

  @override
  bool get isThrottled => (super.noSuchMethod(
        Invocation.getter(#isThrottled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [MuxedStreamInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockMuxedStreamInfo extends _i1.Mock implements _i6.MuxedStreamInfo {
  @override
  _i6.VideoId get videoId => (super.noSuchMethod(
        Invocation.getter(#videoId),
        returnValue: _FakeVideoId_10(
          this,
          Invocation.getter(#videoId),
        ),
        returnValueForMissingStub: _FakeVideoId_10(
          this,
          Invocation.getter(#videoId),
        ),
      ) as _i6.VideoId);

  @override
  int get tag => (super.noSuchMethod(
        Invocation.getter(#tag),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  Uri get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _FakeUri_19(
          this,
          Invocation.getter(#url),
        ),
        returnValueForMissingStub: _FakeUri_19(
          this,
          Invocation.getter(#url),
        ),
      ) as Uri);

  @override
  _i6.StreamContainer get container => (super.noSuchMethod(
        Invocation.getter(#container),
        returnValue: _FakeStreamContainer_20(
          this,
          Invocation.getter(#container),
        ),
        returnValueForMissingStub: _FakeStreamContainer_20(
          this,
          Invocation.getter(#container),
        ),
      ) as _i6.StreamContainer);

  @override
  _i6.FileSize get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: _FakeFileSize_21(
          this,
          Invocation.getter(#size),
        ),
        returnValueForMissingStub: _FakeFileSize_21(
          this,
          Invocation.getter(#size),
        ),
      ) as _i6.FileSize);

  @override
  _i6.Bitrate get bitrate => (super.noSuchMethod(
        Invocation.getter(#bitrate),
        returnValue: _FakeBitrate_22(
          this,
          Invocation.getter(#bitrate),
        ),
        returnValueForMissingStub: _FakeBitrate_22(
          this,
          Invocation.getter(#bitrate),
        ),
      ) as _i6.Bitrate);

  @override
  String get audioCodec => (super.noSuchMethod(
        Invocation.getter(#audioCodec),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#audioCodec),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#audioCodec),
        ),
      ) as String);

  @override
  String get videoCodec => (super.noSuchMethod(
        Invocation.getter(#videoCodec),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#videoCodec),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#videoCodec),
        ),
      ) as String);

  @override
  _i6.VideoQuality get videoQuality => (super.noSuchMethod(
        Invocation.getter(#videoQuality),
        returnValue: _i6.VideoQuality.unknown,
        returnValueForMissingStub: _i6.VideoQuality.unknown,
      ) as _i6.VideoQuality);

  @override
  _i6.VideoResolution get videoResolution => (super.noSuchMethod(
        Invocation.getter(#videoResolution),
        returnValue: _FakeVideoResolution_23(
          this,
          Invocation.getter(#videoResolution),
        ),
        returnValueForMissingStub: _FakeVideoResolution_23(
          this,
          Invocation.getter(#videoResolution),
        ),
      ) as _i6.VideoResolution);

  @override
  _i6.Framerate get framerate => (super.noSuchMethod(
        Invocation.getter(#framerate),
        returnValue: _FakeFramerate_24(
          this,
          Invocation.getter(#framerate),
        ),
        returnValueForMissingStub: _FakeFramerate_24(
          this,
          Invocation.getter(#framerate),
        ),
      ) as _i6.Framerate);

  @override
  _i11.MediaType get codec => (super.noSuchMethod(
        Invocation.getter(#codec),
        returnValue: _FakeMediaType_25(
          this,
          Invocation.getter(#codec),
        ),
        returnValueForMissingStub: _FakeMediaType_25(
          this,
          Invocation.getter(#codec),
        ),
      ) as _i11.MediaType);

  @override
  String get qualityLabel => (super.noSuchMethod(
        Invocation.getter(#qualityLabel),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#qualityLabel),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#qualityLabel),
        ),
      ) as String);

  @override
  String get videoQualityLabel => (super.noSuchMethod(
        Invocation.getter(#videoQualityLabel),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#videoQualityLabel),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#videoQualityLabel),
        ),
      ) as String);

  @override
  List<_i16.Fragment> get fragments => (super.noSuchMethod(
        Invocation.getter(#fragments),
        returnValue: <_i16.Fragment>[],
        returnValueForMissingStub: <_i16.Fragment>[],
      ) as List<_i16.Fragment>);

  @override
  bool get isThrottled => (super.noSuchMethod(
        Invocation.getter(#isThrottled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [AudioOnlyStreamInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioOnlyStreamInfo extends _i1.Mock
    implements _i6.AudioOnlyStreamInfo {
  @override
  _i6.VideoId get videoId => (super.noSuchMethod(
        Invocation.getter(#videoId),
        returnValue: _FakeVideoId_10(
          this,
          Invocation.getter(#videoId),
        ),
        returnValueForMissingStub: _FakeVideoId_10(
          this,
          Invocation.getter(#videoId),
        ),
      ) as _i6.VideoId);

  @override
  int get tag => (super.noSuchMethod(
        Invocation.getter(#tag),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  Uri get url => (super.noSuchMethod(
        Invocation.getter(#url),
        returnValue: _FakeUri_19(
          this,
          Invocation.getter(#url),
        ),
        returnValueForMissingStub: _FakeUri_19(
          this,
          Invocation.getter(#url),
        ),
      ) as Uri);

  @override
  _i6.StreamContainer get container => (super.noSuchMethod(
        Invocation.getter(#container),
        returnValue: _FakeStreamContainer_20(
          this,
          Invocation.getter(#container),
        ),
        returnValueForMissingStub: _FakeStreamContainer_20(
          this,
          Invocation.getter(#container),
        ),
      ) as _i6.StreamContainer);

  @override
  _i6.FileSize get size => (super.noSuchMethod(
        Invocation.getter(#size),
        returnValue: _FakeFileSize_21(
          this,
          Invocation.getter(#size),
        ),
        returnValueForMissingStub: _FakeFileSize_21(
          this,
          Invocation.getter(#size),
        ),
      ) as _i6.FileSize);

  @override
  _i6.Bitrate get bitrate => (super.noSuchMethod(
        Invocation.getter(#bitrate),
        returnValue: _FakeBitrate_22(
          this,
          Invocation.getter(#bitrate),
        ),
        returnValueForMissingStub: _FakeBitrate_22(
          this,
          Invocation.getter(#bitrate),
        ),
      ) as _i6.Bitrate);

  @override
  String get audioCodec => (super.noSuchMethod(
        Invocation.getter(#audioCodec),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#audioCodec),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#audioCodec),
        ),
      ) as String);

  @override
  _i11.MediaType get codec => (super.noSuchMethod(
        Invocation.getter(#codec),
        returnValue: _FakeMediaType_25(
          this,
          Invocation.getter(#codec),
        ),
        returnValueForMissingStub: _FakeMediaType_25(
          this,
          Invocation.getter(#codec),
        ),
      ) as _i11.MediaType);

  @override
  List<_i16.Fragment> get fragments => (super.noSuchMethod(
        Invocation.getter(#fragments),
        returnValue: <_i16.Fragment>[],
        returnValueForMissingStub: <_i16.Fragment>[],
      ) as List<_i16.Fragment>);

  @override
  String get qualityLabel => (super.noSuchMethod(
        Invocation.getter(#qualityLabel),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#qualityLabel),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#qualityLabel),
        ),
      ) as String);

  @override
  bool get isThrottled => (super.noSuchMethod(
        Invocation.getter(#isThrottled),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
        returnValueForMissingStub: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
