// Mocks generated by Mockito 5.4.4 from annotations
// in youtube_music_downloader/test/features/download_setup/presentation/providers/download_setup_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:youtube_music_downloader/features/download_setup/domain/entities/media_metadata.dart'
    as _i2;
import 'package:youtube_music_downloader/features/download_setup/domain/repositories/download_setup_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMediaMetadata_0 extends _i1.SmartFake implements _i2.MediaMetadata {
  _FakeMediaMetadata_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DownloadSetupRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadSetupRepository extends _i1.Mock
    implements _i3.DownloadSetupRepository {
  @override
  _i4.Future<_i2.MediaMetadata> fetchMetadata(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMetadata,
          [url],
        ),
        returnValue: _i4.Future<_i2.MediaMetadata>.value(_FakeMediaMetadata_0(
          this,
          Invocation.method(
            #fetchMetadata,
            [url],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.MediaMetadata>.value(_FakeMediaMetadata_0(
          this,
          Invocation.method(
            #fetchMetadata,
            [url],
          ),
        )),
      ) as _i4.Future<_i2.MediaMetadata>);
}
