// Mocks generated by Mockito 5.4.4 from annotations
// in youtube_music_downloader/test/features/downloads_history/presentation/providers/history_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:youtube_music_downloader/features/downloads_history/data/models/download_task.dart'
    as _i4;
import 'package:youtube_music_downloader/features/downloads_history/domain/repositories/downloads_history_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DownloadsHistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadsHistoryRepository extends _i1.Mock
    implements _i2.DownloadsHistoryRepository {
  @override
  _i3.Future<_i4.DownloadTask?> getTaskById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTaskById,
          [id],
        ),
        returnValue: _i3.Future<_i4.DownloadTask?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.DownloadTask?>.value(),
      ) as _i3.Future<_i4.DownloadTask?>);

  @override
  _i3.Future<_i4.DownloadTask?> getNextPendingTask() => (super.noSuchMethod(
        Invocation.method(
          #getNextPendingTask,
          [],
        ),
        returnValue: _i3.Future<_i4.DownloadTask?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.DownloadTask?>.value(),
      ) as _i3.Future<_i4.DownloadTask?>);

  @override
  _i3.Future<void> saveTask(_i4.DownloadTask? task) => (super.noSuchMethod(
        Invocation.method(
          #saveTask,
          [task],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateTaskProgress(
    int? id, {
    required double? progress,
    required String? speed,
    required String? eta,
    required _i4.DownloadStatus? status,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTaskProgress,
          [id],
          {
            #progress: progress,
            #speed: speed,
            #eta: eta,
            #status: status,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateTaskStatus(
    int? id,
    _i4.DownloadStatus? status, {
    String? errorMessage,
    String? actualQuality,
    String? targetPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTaskStatus,
          [
            id,
            status,
          ],
          {
            #errorMessage: errorMessage,
            #actualQuality: actualQuality,
            #targetPath: targetPath,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.DownloadTask>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.DownloadTask>>.value(<_i4.DownloadTask>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.DownloadTask>>.value(<_i4.DownloadTask>[]),
      ) as _i3.Future<List<_i4.DownloadTask>>);

  @override
  _i3.Stream<List<_i4.DownloadTask>> watchAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #watchAllTasks,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.DownloadTask>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i4.DownloadTask>>.empty(),
      ) as _i3.Stream<List<_i4.DownloadTask>>);

  @override
  _i3.Future<void> deleteTask(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
